### ISSUE TITLE
Depends on ros-build-tools

### ISSUE THREAD

**Issue by thezealousfool** [ros-melodic-arch/ros-melodic-catkin#1]
Seems like it depends on ros-build-tools.

**Comment by bionade24** [comment]
Yes, I removed it to check if there any python2 Deps in my packages. I wanted to already have a py3 successor, but I didn't have time yet. Will fixed until tomorrow.

**Comment by bionade24** [comment]
Fixed in https://github.com/ros-melodic-arch/ros-melodic-catkin/commit/4b14d1af4e18e065bce3dc01d568c244af8b5f61
