### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-catkin#4]

**Comment by bionade24** [comment]
Just for the public: The problem is that catkin 0.8 doesn't build with the current gmock filesystem layout. So I decided to hold the update back for some time so that users don't run into issues. If you want, you can easily edit the `pkgver` and `sha256sums` yourself.

**Comment by bionade24** [comment]
@acxz Can't reproduce the build issues you had with regular gmock and gtest on the CI and on my local machine. Will sync.
