### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by michtesar** [ros-melodic-arch/ros-melodic-catkin#6]
Hi I found that some dependencies are not reachable:
- change `python-empy` to `python2-empy` and install `pip install --user --upgrade empty`
- I was able to install pkg `python-catkin_pkg` and `ros-build-tools-py3` with `yay` but directly

**Comment by michtesar** [comment]
I haven't check there is `arch4edu` repository which has all dependencies. Sorry for creating issue. Closing.

**Comment by jwhendy** [comment]
Looks like you've sorted this out, but I just wanted to comment that 1) I don't think pulling in the `python2` version of anything should be a fix and 2) I don't have `arch4edu` as a repo and things still work for me. You may want to check your overall system `python2` vs. `python3` status.
